### ISSUE TITLE
Old Footnotes in Exhibits

### ISSUE THREAD

**Issue by yee-luna-c** [alexanderlewis99/TinyMCEMod#1]
Some pages on old exhibits are still marked with old footnote syntax. In many cases, due to the complexity of adding footnotes before TinyMCEMod's introduction, these footnotes were not up to form (often with repeating [1] notes).

For these pages, the TinyMCEMod footnote buttons will not work, and may cause additional issues. In particular, it would seem that `update footnotes` usually has no effect on the existing footnotes, and that `add footnote` may invalidate some previous footnotes (which `update footnotes` cannot fix).

To illustrate, consider the Watt Munisotaram exhibit's page on Cambodian Immigration: [edit view](http://omeka-dev.carleton.edu/religionsmn/admin/exhibits/edit-page/1401) | [live view](http://omeka-dev.carleton.edu/religionsmn/exhibits/show/wattmunisotaram/history/cambodiaimmigration). While the live version of the page shows up as it should, the source code does not respond well to footnotes added in the new style.

**Comment by apjmason** [comment]
Looks like there are multiple footnote divs and ols in that list hence the restarting at 1.

**Comment by alexanderlewis99** [comment]
Hi. Thanks for bringing this issue to light. I have addressed it in the following ways: (1) all existing footnotes links are assigned the class "footnote link" (all new ones are already born with this class); (2) if multiple footnote divs exist, they are merged together and then their respective ols are then merged together. Order is preserved in this process to create as little disruption as possible. As a test, the update footnote button now works on the Cambodian Immigration page as well as others.

**Comment by apjmason** [comment]
This is looking good! One lingering issue, however, and this might have been there all along. 

The Update Footnotes button updates the href link numbers that the bigfoot plugin is looking for, so they all work right on public view. But it doesn't actually reorder the notes in the footnotes div ordered list. This is confusing, since it means the human readable numbers in the editor don't line up with the numbers of the note links. 

Compare the wysiwyg and code views below of [this testing page](http://omeka-dev.carleton.edu/religionsmn/admin/exhibits/edit-page/1831)

![Screen Shot 2019-04-19 at 6 44 38 AM](https://user-images.githubusercontent.com/10544799/56423570-54340580-6272-11e9-87a1-92eec37b5301.JPG)

![Screen Shot 2019-04-19 at 7 12 53 AM](https://user-images.githubusercontent.com/10544799/56423629-a6752680-6272-11e9-8bdf-8527bde6c4f1.JPG)

Can we actually reorder the list entries @alexanderlewis99 ?

**Comment by alexanderlewis99** [comment]
Hi! I updated the plugin so that it adjusts the order of the footnotes in footnotes-div-ordered-list to match the new order of the footnote links. I set up an example here [on this testing page](http://omeka-dev.carleton.edu/religionsmn/admin/exhibits/edit-page/1834) of how it updates the order. Let me know if this sufficiently solves the problem. Thanks!

**Comment by yee-luna-c** [comment]
The reordering of footnotes in the list looks like it's causing a bit of an issue. While editing, it appears to be working.
![image](https://user-images.githubusercontent.com/43069771/56865885-b094d480-6998-11e9-98a9-4656cec4ca1b.png)
However, the product after reordering also shuffles the footnotes.
![image](https://user-images.githubusercontent.com/43069771/56865882-a246b880-6998-11e9-916b-a1f9f3dc2984.png)
I believe the issue lies with the <a> links on the footnotes themselves. It seems that they aren't updated while the labels of the footnotes are.
![image](https://user-images.githubusercontent.com/43069771/56865927-30bb3a00-6999-11e9-9a64-c98718d70162.png)
With any luck, this is a simple "resolve any references" type of fix.

A couple extra notes I jotted down while checking over this:

Is a "Delete Footnote" function something that could be added? I think the students may have the need to delete footnotes, and the process to do so right now is essentially: fully delete both the footnote link and footnote reference. However, this is a lot to ask, since there can be formatting that remains.
![image](https://user-images.githubusercontent.com/43069771/56865994-0027d000-699a-11e9-8067-7d7d7ce30b07.png)
![image](https://user-images.githubusercontent.com/43069771/56866000-133aa000-699a-11e9-8e91-a12643e7352f.png)

Also, there's a space and period placed after the footnote link when using "Add Footnote." Is this purposeful? It also seems to be part of the reason for the potential lingering formatting noted above.
![image](https://user-images.githubusercontent.com/43069771/56866027-86dcad00-699a-11e9-9747-6b829213c8c8.png)

**Comment by alexanderlewis99** [comment]
I rewrote the sorting algorithm such that it now keeps track of all the IDs and reorders them properly. It takes into account cases such as deleted links, deleted citations, and extras of both. I also added a "Delete Selected Footnotes" button which will delete all footnotes the user has highlighted in the text field. Let me know if this solves the considered existing and potential issues.

**Comment by apjmason** [comment]
Alec, great work! Another potential wrinkle: I realized some pages have footnotes in multiple blocks so that you might have 1 and 2 in block one, then a file block, then another block with 3 and 4. Can we add a start numbering from option?

**Comment by alexanderlewis99** [comment]
Hi Austin. I added a start numbering option to the footnote plugin. You can see an example of a page with footnotes across multiple TinyMCE editors here: http://omeka-dev.carleton.edu/religionsmn/admin/exhibits/edit-page/1829. Let me know if this matches what you had in mind. Thanks!

**Comment by apjmason** [comment]
Looks great! Fixed in 58da655e4008aabf095d3df6021dd01504409a62 and subsequent 3 commits.
